services:
  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "8200:80"
    networks:
      - app-network

  cache:
    build:
      context: cache
      dockerfile: Dockerfile
    volumes:
      - nginx-cache:/var/cache/nginx
    ports:
      - "8201:80"
    networks:
      - app-network

  worker-wrapper:
    build:
      context: worker-wrapper
      dockerfile: Dockerfile
    ports:
      - "8202:8000"
    networks:
      - app-network
  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    ports:
      - "8203:8000"
    networks:
      - app-network
volumes:

  nginx-cache:

networks:
  app-network:
    driver: bridge